spring:
  profiles:
    include:
      - db
  main:
    allow-bean-definition-overriding: true

mybatis:
  mapper-locations: classpath*:/mapper/*.xml
  type-aliases-package: com.eunhasoo.board.domain

logging:
  level:
    root: INFO
    com.eunhasoo: DEBUG
    com.eunhasoo.board.mapper: DEBUG
    jdbc.sqlonly: DEBUG

# disable default white label error page
server:
  error:
    whitelabel:
      enabled: false
    include-stacktrace: always